- hosts: localhost
  vars:
     env: dev
  tasks:
   - name: Nested Loop Demo
     debug:
         msg: "{{item[0]}}-{{item[1]}}"
     with_nested:
      - [ 'Section-1', 'Section-2' ]
      - [ 'Part-I', 'Part-II', 'Part-III' ]

